AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  LeaderboardServer
  
  SAM Template for LeaderboardServer

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10

Resources:
  EntryApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/lambda/cmd
      Handler: EntryApi
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: any
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
          LEADERBOARD_TABLE_NAME: !Ref LeaderboardTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref LeaderboardTable

  LeaderboardTable:
    Type: AWS::Serverless::SimpleTable # More info about SimpleTable Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html
    # If no ProvisionedThroughput then BillingMode: PAY_PER_REQUEST
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EntryAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/entry/"
  EntryApiFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt EntryApiFunction.Arn
  EntryApiFunctionIamRole:
    Description: "Implicit IAM Role created for EntryAPI function"
    Value: !GetAtt EntryApiFunctionRole.Arn
